[tool.poetry]
name = "conductor"
version = "0.1.0"
description = ""
authors = ["csmizzle <chrissmith700@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
langchain = "^0.1.14"
boto3 = "^1.34.77"
requests = "^2.31.0"
langchain-community = "^0.0.31"
openai = "^1.16.1"
langgraph = "^0.0.31"
langchain-openai = "^0.1.1"
wikipedia = "^1.4.0"
langchainhub = "^0.1.15"
discord-py = "^2.3.2"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
