[tool.poetry]
name = "conductor"
version = "0.1.13"
description = ""
authors = ["csmizzle <chrissmith700@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
langchain = "^0.1.14"
boto3 = "^1.34.77"
requests = "^2.31.0"
langchain-community = "^0.0.31"
openai = "^1.16.1"
langgraph = "^0.0.31"
langchainhub = "^0.1.15"
discord-py = "^2.3.2"
boto3-stubs = {extras = ["essential"], version = "^1.34.83"}
pinecone-client = "^3.2.2"
langchain-pinecone = "^0.1.0"
fire = "^0.6.0"
langsmith = "^0.1.50"
agentops = "^0.1.6"
pytest = "^8.1.1"
crewai = {extras = ["tools"], version = "^0.30.11"}
jmespath = "^1.0.1"
google-auth-oauthlib = "^1.2.0"
google-api-python-client = "^2.127.0"
scrapy = "^2.11.1"
apify = {extras = ["scrapy"], version = "^1.7.0"}
nest-asyncio = "^1.6.0"
bs4 = "^0.0.2"
langchain-fireworks = "^0.1.2"
billiard = "^4.2.0"
anthropic = "^0.25.8"
pdfkit = "^1.0.0"
google-search-results = "^2.4.2"
jinja2 = "^3.1.4"
redis = "^5.0.7"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
pyyaml = "^6.0.1"
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
